### ISSUE TITLE
wiki page

### ISSUE THREAD

**Issue by yujiny97** [GrapeCandy/Assignment2#12]
wiki page를 작성할때 # 을 한다면 글자의 크기를 크게 할 수 있습니다. 그리고 * 를 한다면 dot이 만들어 집니다. 그리고 줄바꿈을 해야 할때에는 두번 줄바꿈을 해야지만 한번 줄바꿈이 된다는 것을 알 수 있었습니다. 하지만 문제점은 wikipage를 clone을 하여 pull request를 조장님의 repository에 해보려 했지만 code 창의 파일이 아니여서 request를 할 수 없었습니다. 인터넷에서도 찾아보았으나 wikipage는 pull request를 지원하지 않는다고 하였습니다.

**Comment by GrapeCandy** [comment]
Very nice comment!
