### ISSUE TITLE
두 개의 파일의 크기를 비교하는법

### ISSUE THREAD

**Issue by ohnamhun** [GrapeCandy/Assignment2#9]
http://bodamnury.tistory.com/38
c언어에서 제공하는 파일 정보 구조체 struct stat이 있습니다.
구조체 stat 내부에 있는 st_size라는 파일의 size를 저장하고 있는 변수를 비교하여
파일의 크기를 비교할 수 있습니다.

**Comment by GrapeCandy** [comment]
함수 1의 stat에서 받아온 정보를 사용하는군요!
